general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blur_size = 8

    brightness = 0.55
    vibrancy = 0.15
}

# BIG CLOCK
label {
    monitor =
    text = $TIME
    color = rgba(205, 214, 244, 1.0)

    font_size = 90
    font_family = JetBrainsMono Nerd Font

    position = 0, 170
    halign = center
    valign = center

    shadow_passes = 2
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date "+%A, %B %d"
    color = rgba(166, 173, 200, 1.0)

    font_size = 20
    font_family = JetBrainsMono Nerd Font

    position = 0, 90
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = $USER
    color = rgba(137, 180, 250, 1.0)

    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, 15
    halign = center
    valign = center
}

# PASSWORD BOX
input-field {
    monitor =

    size = 320, 55
    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true

    outer_color = rgba(137, 180, 250, 0.9)
    inner_color = rgba(30, 30, 46, 0.75)
    font_color = rgba(205, 214, 244, 1.0)

    font_family = JetBrainsMono Nerd Font

    placeholder_text = <i>Password...</i>

    fade_on_empty = false
    rounding = 15

    check_color = rgba(166, 227, 161, 1.0)
    fail_color = rgba(243, 139, 168, 1.0)

    position = 0, -60
    halign = center
    valign = center

    shadow_passes = 2
}
